server.port=8080
spring.application.name=webauthn-attestation-simple

app.relying-party-id=localhost
app.relying-party-name=Attestation Demo
app.relying-party-origins=http://localhost:8080

spring.jackson.serialization.indent-output=true